import ThemeProvider from '@/Providers/ThemeProvider';
import './globals.css';
import { Toaster } from 'sonner';
import { dbConnect } from '@/lib/mongo';

export const metadata = {
    title: 'Wifi Hotspot',
    description: 'Generated by Wifi Hotspot'
};

export default async function RootLayout({ children }) {
    // Connect to MongoDB database
    const cont = await dbConnect();
    return (
        <html lang='en'>
            <body>
                <ThemeProvider>{children}</ThemeProvider>
                <Toaster />
            </body>
        </html>
    );
}
