import ThemeProvider from '@/Providers/ThemeProvider';
import './globals.css';
import { Toaster } from 'sonner';

export const metadata = {
    title: 'Wifi Hotspot',
    description: 'Generated by Wifi Hotspot'
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>
                <ThemeProvider>{children}</ThemeProvider>
                <Toaster />
            </body>
        </html>
    );
}
